=== Rymond3/ABD/xquery/CUSTOMERS_ON.dtd
<!ELEMENT SALES((CUSTOMERS+))>
<!ELEMENT CUSTOMERS ((CUSTOMERNUMBER, CUSTOMERNAME, CONTACTLASTNAME, CONTACTFIRSTNAME, PHONE, ADDRESS, SALESREPEMPLOYEENUMBER, CREDITLIMIT, ORDERS))>
<!ELEMENT CUSTOMERNUMBER EMPTY>
<!ELEMENT CUSTOMERNAME(#PCDATA)>
<!ELEMENT CONTACLASTNAME(#PCDATA)>
<!ELEMENT CONTACTFIRSTNAME(#PCDATA)>
<!ELEMENT PHONE( #PCDATA)>
<!ELEMENT ADDRESS ((ADDRESSLINE1, ADDRESSLINE2?, CITY, STATE?, POSTALCODE, COUNTRY))>
<!ELEMENT ADDRESSLINE1 (#PCDATA)>
<!ELEMENT ADDRESSLINE2 (#PCDATA)>
<!ELEMENT CITY (#PCDATA)>
<!ELEMENT STATE (#PCDATA)>
<!ELEMENT POSTALCODE (#PCDATA)>
<!ELEMENT COUNTRY (#PCDATA)>
<!ELEMENT SALESREPEMPLOYEENUMBER (#PCDATA)>
<!ELEMENT CREDITLIMIT (#PCDATA)>
<!ELEMENT ORDERS ((ORDER+))>
<!ELEMENT ORDER ((PRICE))>
<!ELEMENT PRICE (#PCDATA)>
<!ATTLIST CUSTOMERNUMBER id CDATA #REQUIRED card (silver | gold | bronce) #REQUIRED>
<!ATTLIST ORDER number CDATA #REQUIRED status (pending | open | closed) #REQUIRED currency (pounds | euros | dollars) #REQUIRED>

=== Rymond3/ABD/xquery/CUSTOMERS_ON.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SALES SYSTEM "CUSTOMERS_ON.dtd">
<SALES>
	<CUSTOMERS>
		<CUSTOMERNUMBER id="103" card="silver"/>
		<CUSTOMERNAME>Atelier graphique</CUSTOMERNAME>
		<CONTACTLASTNAME>Schmitt</CONTACTLASTNAME>
		<CONTACTFIRSTNAME>Carine</CONTACTFIRSTNAME>
		<PHONE>40.32.2555</PHONE>
		<ADDRESS>
			<ADDRESSLINE1>54, rue Royale</ADDRESSLINE1>
			<ADDRESSLINE2></ADDRESSLINE2>
			<CITY>Nantes</CITY>
			<STATE></STATE>
			<POSTALCODE>44000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
		</ADDRESS>
		<SALESREPEMPLOYEENUMBER>1370</SALESREPEMPLOYEENUMBER>
		<CREDITLIMIT>21000</CREDITLIMIT>
		<ORDERS>
			<ORDER number="0001" status="open" currency="euros">
				<PRICE>10000</PRICE>
			</ORDER>
			<ORDER number="0002" status="closed" currency="dollars">
				<PRICE>20000</PRICE>
			</ORDER>
			<ORDER number="0003" status="pending" currency="pounds">
				<PRICE>30000</PRICE>
			</ORDER>
		</ORDERS>
	</CUSTOMERS>
	<CUSTOMERS>
		<CUSTOMERNUMBER id="112" card="gold"/>
		<CUSTOMERNAME>Signal Gift Stores</CUSTOMERNAME>
		<CONTACTLASTNAME>King</CONTACTLASTNAME>
		<CONTACTFIRSTNAME>Sue</CONTACTFIRSTNAME>
		<PHONE>7025551838</PHONE>
		<ADDRESS>
			<ADDRESSLINE1>8489 Strong St.</ADDRESSLINE1>
			<ADDRESSLINE2></ADDRESSLINE2>
			<CITY>Las Vegas</CITY>
			<STATE></STATE>
			<POSTALCODE>83030</POSTALCODE>
			<COUNTRY>USA</COUNTRY>
		</ADDRESS>
		<SALESREPEMPLOYEENUMBER>1166</SALESREPEMPLOYEENUMBER>
		<CREDITLIMIT>71800</CREDITLIMIT>
		<ORDERS>
			<ORDER number="0001" status="open" currency="euros">
				<PRICE>10000</PRICE>
			</ORDER>
			<ORDER number="0002" status="closed" currency="dollars">
				<PRICE>15000</PRICE>
			</ORDER>
		</ORDERS>
	</CUSTOMERS>
	<CUSTOMERS>
	<CUSTOMERNUMBER id="114" card="bronce"/>
		<CUSTOMERNAME>Australian Collectors, Co.</CUSTOMERNAME>
		<CONTACTLASTNAME>Ferguson</CONTACTLASTNAME>
		<CONTACTFIRSTNAME>Peter</CONTACTFIRSTNAME>
		<PHONE>03 9520 4555</PHONE>
		<ADDRESS>
			<ADDRESSLINE1>636 St Kilda Road</ADDRESSLINE1>
			<ADDRESSLINE2>Level 3</ADDRESSLINE2>
			<CITY>Melbourne</CITY>
			<STATE>Victoria</STATE>
			<POSTALCODE>3004</POSTALCODE>
			<COUNTRY>Australia</COUNTRY>
		</ADDRESS>
		<SALESREPEMPLOYEENUMBER>1611</SALESREPEMPLOYEENUMBER>
		<CREDITLIMIT>117300</CREDITLIMIT>
		<ORDERS>
			<ORDER number="0001" status="open" currency="euros">
				<PRICE>7000</PRICE>
			</ORDER>
			<ORDER number="0002" status="pending" currency="euros">
				<PRICE>14000</PRICE>
			</ORDER>
		</ORDERS>
	</CUSTOMERS>
	
<CUSTOMERS>
		<CUSTOMERNUMBER id="119" card="silver"/>
		<CUSTOMERNAME>La Rochelle Gifts</CUSTOMERNAME>
		<CONTACTLASTNAME>Labrune</CONTACTLASTNAME>
		<CONTACTFIRSTNAME>Janine</CONTACTFIRSTNAME>
		<PHONE>40.67.8555</PHONE>
		<ADDRESS>
			<ADDRESSLINE1>67, rue des Cinquante Otages</ADDRESSLINE1>
			<ADDRESSLINE2></ADDRESSLINE2>
			<CITY>Nantes</CITY>
			<STATE></STATE>
			<POSTALCODE>44000</POSTALCODE>
			<COUNTRY>France</COUNTRY>
		</ADDRESS>
		<SALESREPEMPLOYEENUMBER>1370</SALESREPEMPLOYEENUMBER>
		<CREDITLIMIT>118200</CREDITLIMIT>
		<ORDERS>
			<ORDER number="0001" status="open" currency="euros">
				<PRICE>14000</PRICE>
			</ORDER>
			<ORDER number="0002" status="closed" currency="euros">
				<PRICE>35000</PRICE>
			</ORDER>
		</ORDERS>
	</CUSTOMERS>	
</SALES>
